name: trade

dependencies:
  - python = 3.11
  - pip
  - pip:
    - fastapi==0.103.1
    - uvicorn[standard]==0.23.2
    - sqlmodel==0.0.16
    - httpx==0.25.0
    - parameterized == 0.9.0

variables:
  PYTHONPATH: .
